### PR TITLE
UX and Test Improvements

### PR DESCRIPTION
**Pull request by elcritch**
There's a few different UX improvements in this PR: progress spinner, colorized and prettified `nimble deps`, and an inverted deps format `nimble deps --format=inverted`.

## Progress Spinner 

Nimble can take a while to check git for package caches now among other things, which can lead to frustration not knowing if Nimble is working or hung on some repo.

This PR adds a spinner style progress indicator to make these waits less annoying. The progress is based on suppressed debug messages which gives a good cadence to the work being done.

The spinner is just a simple `    Working  ⡿` style one, not a percentage one. It only shows when using `noColor` is not set.

image

## Deps Tree

It's colorized and outputs a nice tree format borrowing from Cargo, NPM, etc.

image

## Inverted Deps Tree

It's *really* helpful to print each dependency for a project and what requirements led to the resolved version.

image

### CODE REVIEW

**Comment by arnetheduck** [comment]
This is nice - nimble is way way way way too verbose and fills the screen with useless junk for basically anything it does - it should not be wasting vertical space on "I actually managed to perform the task you asked me to" as if this was a surprise, every time.

> The spinner is just a simple

instead of "working", it could show what it's doing (ie `Scanning xyz` or `Cloning ...`)

**Comment by arnetheduck** [comment]
> some line matching

this sounds like a maintenance nightmare though - maybe better leave it as is until a more deliberate source of information can be developed

**Comment by elcritch** [comment]
> this sounds like a maintenance nightmare though - maybe better leave it as is until a more deliberate source of information can be developed

It could be. It shouldn't result in anything breaking just going to the default "Working". 

I added it as I was curious and it doesn't seem _too_ bad. Does make it nicer to know it's "Scanning" (printPkgInfo) or "Updating" (git ls-remote).

Though the idea is nice, I'll probably revert it. It'd be better and probably not too hard to pipe the info in via the `doCmd` pieces.

**Comment by elcritch** [comment]
@jmgomez this is ready. Not sure who's reviewing these things nowadays so figured I'd ping you.

**Comment by jmgomez** [comment]
Looks good to me. But @Araq is the one approving for the time being :)

**Pull request merged**
