### PR TITLE
for a sense of unity.

### PR DESCRIPTION
**Pull request by shinriyo**
another is .nimble. so I modified.

### CODE REVIEW

**Comment by dom96** [comment]
Upvoting your own PR won't make it more likely to be merged ;)

The current error message is fine. What would be a welcome improvement is appending the filename of the Nimble file: ``Nimble file already exists: /home/user/projects/foo/foo.nimble``

**Comment by shinriyo** [comment]
@dom96 
I did your feedback.

**Comment by dom96** [comment]
Still not 100%, but I made the necessary changes.

**Comment by shinriyo** [comment]
@dom96 yes it is better.

**Pull request merged**
