### PR TITLE
Fix wrong version detection in listPaths.

### PR DESCRIPTION
**Pull request by BopoHDark**
In case we have packages with same name and aone of them has nimble-link(as result of nimble develop i.e.), version of package with nimble-link will be the same as version of package which that link targets.This leads to wrong nimble path results when you have developed and installed versions of the package.

### CODE REVIEW

**Comment by dom96** [comment]
Yay! Beautiful! Thank you for using the ``getInstalledPkgsMin`` function, should have been done in the first place :)

**Comment by dom96** [comment]
If you could resolve the conflicts I will merge it immediately. Otherwise will wait until I'm working on the next release.

**Comment by BopoHDark** [comment]
Done. Sorry couldn't do this earlier.

**Comment by BopoHDark** [comment]
One of tests of *[Suite] develop feature*, test "can develop with srcDir" is broken. I don't know how to fix it, it calls develop in directory "develop/srcdirtest", and after that checks path "develop/srcdirtest/src".

**Comment by dom96** [comment]
Well... it was passing before. Do you think the test is incorrect?

[Link to test failure](https://travis-ci.org/nim-lang/nimble/builds/355320410#L909)

**Comment by BopoHDark** [comment]
Problem was in srcDir field witch is "" for package which isLinked, so getRealDir does not return proper path.
I've tryed to workaround this, but after my commit tests are failed, when my local tests is ok. :(

**Comment by dom96** [comment]
No worries, I'll look into it later.

**Comment by Vindaar** [comment]
I rebased this PR on the current master locally to check whether it solves a problem I had: 
Running `nimble path` on an installed package returned the `srcDir` appended to the path, even though it shouldn't. The reason was that `isLinked` and `isInstalled` are not set in the current master ins `listPaths`. In line https://github.com/nim-lang/nimble/blob/master/src/nimble.nim#L640 the call to `getRealDir` then returns the `srcDir` appended, since `isInstalled` is falsely false.

Since this PR uses `getInstalledPkgsMin` in `listPaths` instead of walking the directory, `isInstalled` and `isLinked` (thanks to the introduced `getLinkedSrcDir`) are properly set and the `srcDir` doesn't show up.

I ran `nimble test` locally and do not see any errors. 

And if I'm not mistaken the issue #393 / lines https://github.com/nim-lang/nimble/blob/master/src/nimble.nim#L193-L196 can now be fixed with this too, since `srcDir` is now properly set.

**Pull request closed without merging**
