### PR TITLE
Updated fix for #280 with dependencies

### PR DESCRIPTION
**Pull request by genotrance**
Original fix ran "before install" before dependencies were installed.

### CODE REVIEW

**Comment by genotrance** [comment]
I don't see why #280 got linked to these unrelated comments. Regardless, this updated fix has a new issue - if you run `nimble install` on a package in a local directory, it runs `before install` twice since the execHook() runs in doAction() as well as inside install().

I'm thinking we need to keep track of whether before and after hooks have run already or not. I think this can be done by changing PackageInfo.preHook and postHook into Table[string, bool] but it might be overkill. Suggestions appreciated.

**Comment by genotrance** [comment]
I've fixed this by moving the pre and post execHook() calls within installFromDir(). This ensures that it works correctly whether installing locally or after download.

Additionally, I prevent the generic execHook() calls in doAction() from running for actionInstall, similar to actionCustom since they are handled elsewhere.

**Comment by dom96** [comment]
Relevant issue: https://forum.nim-lang.org/t/3949 (which we should also fix)

**Comment by dom96** [comment]
Closing in favour of #482.

**Pull request closed without merging**
