### PR TITLE
Clean up all build files

### LINKED ISSUE #555: Add a `nimble clean` command to clean up build files.
Having a built-in `nimble clean` command that cleans up any test or binary files that have been built via for instance `nimble build` would be nice. Not quite as pressing of an issue now that nimcache in the local directory isn't a thing, but it would still be a huge improvement over having to write

```Nimble
task clean, "Cleans up files":
  exec "rm <project_binary_name_here>"
```

for every project.

### PR DESCRIPTION
**Pull request by xyb**
fix #555

### CODE REVIEW

**Comment by genotrance** [comment]
This is good work, can you please resolve conflicts and resubmit? Thank you.

**Comment by xyb** [comment]
@genotrance @dom96 Sure, I have separated first PR #774.

**Comment by xyb** [comment]
@dom96 @genotrance I removed changes created by nimpretty, now it's included `nimble clean` related only.

**Comment by timotheecour** [comment]
I think this is the wrong approach.

Here are some problems:
* if `nimble test` crashes for whatever reason (maybe even `Control C`), generated files/dirs won't get cleaned up; even on the next run; eg: 
`let existsBefore = existsFile(binFileName)` would be true on next run. This can be addressed, but at the risk of introducing false positives

* the algorithm to find files that should be cleaned up is fragile. Right now it just collects `tfoo` for a file `tfoo.nim`. This won't work if binaries are named differently, or for generated shared libraries or if tests generate other binary or non binary files, as is even the case with nimble's own `nimble test`, which generates other non binary files eg `.json, .nimble, .nims` extensions. This is not unique to nimble's tests, nim's compiler nimble pkg, and others.
* a tool cleaning up files using a complex logic **makes me nervous it could also remove files that should not be removed**, which would be even worse. The logic may not be complex right now but it will be if it intends to reduce those false negatives
* `nimble test` ideally should keep `git status` clean (even before `nimble clean`); this approach doesn't do that

Finally, a use case this prevents is to allow **comparing 2 runs** of `nimble test` and compare the output artifacts.

see https://github.com/nim-lang/nimble/issues/787 for what I'm proposing instead.

**Pull request closed without merging**
