### PR TITLE
nimble install: add --destDir option

### PR DESCRIPTION
**Pull request by CyberTailor**
Requires testing to make sure it works as intended.

This PR closes issue #956

### CODE REVIEW

**Review by dom96 — CHANGES_REQUESTED** [review]
Since we already have `--nimbleDir`, why do we need this?

**Comment by CyberTailor** [comment]
> Since we already have `--nimbleDir`, why do we need this?

It's for package managers, which are usually sandboxed and don't allow direct installation.

`--nimbleDir` (e.g. /opt/nimble) is used to find dependencies in the system root and `--destDir` (e.g. /var/tmp/portage/dev-nim/example/image) is used to install package files to some intermediate location.

If I just set `--nimbleDir` to /var/tmp/..., nimble will be unable to find dependencies.

**Comment by dom96** [comment]
I'm not sure what you mean. If you set `nimbleDir` to `/var/tmp/nimble` it will install all packages in there and find deps just fine

**Comment by dom96** [comment]
I can appreciate that. But it doesn't answer my question: why can't you simply use `--nimbleDir`?

**Comment by CyberTailor** [comment]
> why can't you simply use `--nimbleDir`?

Because there are no dependencies in `/var/tmp/portage/dev-nim/example/image/opt/nimble`, they are in `/opt/nimble`. Things are only installed into this temporary directory, it's not the actual system root.

If I set `--nimbleDir`, nimble will try to find dependencies in `/var/tmp/...` and fail.  
If I don't set it, nimble will attempt to write directly to `/opt/nimble` and fail because system package manager's sandbox won't allow such operation.

**Comment by Flowdalic** [comment]
I think @CyberTailor already did a good job explaining the motivation. But I'd like to add that `DESTDIR` is long standing concept for staged installs. It is defined GNU coding standards - see https://www.gnu.org/prep/standards/html_node/DESTDIR.html#DESTDIR for a good summary [1] - but is found in various other build systems.

<sup>1: Note that it concept probably does predate GNU coding standards</sup>

**Comment by dom96** [comment]
Isn't the real problem here that Nimble doesn't actually have support for multiple Nimble dirs? What we really want is to add support for this first I think. What follows then is a way to specify which Nimble dir packages should be installed in, not this `destDir` which while it seems like it follows GNU conventions, feels like more of a hack to me :)

**Comment by CyberTailor** [comment]
Got it. I'm going to implement support for multiple Nimble dirs then.

**Pull request closed without merging**
