### PR TITLE
Fixed FD leak.

### PR DESCRIPTION
**Pull request by yglukhov**
A nasty one. Took half a day to track down =)

### CODE REVIEW

**Comment by dom96** [comment]
Interesting. How did this manifest itself? Surely the FDs are freed when the Nimble process quits anyway?

**Comment by dom96** [comment]
Also, tests failed, could be because of a recent Nim change though.

**Comment by yglukhov** [comment]
It could be reproduced on 1 mac of 3. Doing nimble install of a package with bin, nim suddenly failed (cannot open system/inclrtl.nim). The bug seemed very obscure to say the least. I've logged errno in open function, and it said 24 (out of file descriptors). So we've searched for the bug in nim at first, then nim lib, and eventually found that fd number is continuosly increasing when running nim through nimble.

**Comment by dom96** [comment]
I see. Sorry about that :)

Nim really needs a ``withFile`` template.

**Comment by yglukhov** [comment]
No worries, i'm really happy i found the problem =)
`withFile` wouldn't really help in this case because CfgParser takes the ownership of the file.

**Comment by yglukhov** [comment]
But proper RAII would probably help =)

**Comment by yglukhov** [comment]
Fixed the tests

**Comment by dom96** [comment]
hah, glad my test suite catched that :D

**Pull request merged**
