### PR TITLE
use GitHub Actions to deploy nimble guide.

### PR DESCRIPTION
**Pull request by daylinmorgan**
This is a follow-up to #1190 to help facilitate this goal "IMO, the content itself can (and should) be improved once this is merged, so others can contribute." 

Switching to instead use a Github Actions Deploy rather than the `gh-pages` branch for the documentation.

I also added a nimscript file at `nimble-guide/config.nims` to make it easier to setup `mkdocs` for hacking on the documentation.

Once merged the "Build and Deployment" source would have to be changed to "Github Actions" and the `gh-pages` branch can be deleted.
screencap

### CODE REVIEW

**Comment by daylinmorgan** [comment]
> Well the docs don't need Python to build so don't claim that they do. `nim rst2html` (maybe it's called `md2html` these days) exists.

Maybe my wording was not specific enough but the documentation at [nim-lang.github.io/nimble](https://nim-lang.github.io/nimble/index.html) is generated using `python` + `mkdocs` (and mkdocs-material). 
Certainly folks can generate html from markdown however they want but it won't replicate how the nimble-guide is actually currently built and served.

**Comment by Araq** [comment]
I don't understand. Ping @ringabout, @narimiran

**Comment by narimiran** [comment]
> Well the docs don't need Python to build so don't claim that they do

Docs don't need it, but this new Nimble Guide does.

----

1. My question (for @daylinmorgan and anybody else) is: Is this really a simpler/better solution than the existing Makefile? (I'm fine either way, but would like to hear more opinions)

2. @daylinmorgan, is https://gh.dayl.in/nimble/ built using this new process? I'd like to make sure everything works before we merge it.

**Comment by ringabout** [comment]
Deployment fialed 

> Branch "master" is not allowed to deploy to github-pages due to environment protection rules.

https://github.com/nim-lang/nimble/actions/runs/8748959902

**Comment by daylinmorgan** [comment]
> Once merged the "Build and Deployment" source would have to be changed to "Github Actions" and the gh-pages branch can be deleted.

Was this changed that I said in the first comment made after PR was merged? 

Additionally, since if the master branch is protected you would need to add it to the `github pages` environment following these steps:

1. Go to you repository Settings.
2. Click on Environments.
3. Select your environment github-pages.
4. Next to Deployment branches select Selected branches from the dropdown.
5. Click on Add deployment branch rule.
6. Enter the pattern "master".

**Comment by narimiran** [comment]
> Was this changed that I said in the first comment made after PR was merged?

Yes.




> Click on Environments.

I don't see that in the settings. It might be that I don't have a full access to this repo, so somebody else (with more priviledges) should follow the steps provided.

**Comment by ringabout** [comment]
Like this?

image

Edited:

Indeed, it works now => https://github.com/nim-lang/nimble/actions/runs/8748959902

**Pull request merged**
