### PR TITLE
Examples support - Draft 2

### PR DESCRIPTION
**Pull request by nais314**
**Draft#2**: Well, i added tests and
moved the examples folder into srcDir - now it gets copied into .nimble/pkgs, but still has a Warning, as  other folder than pkg.name not yet allowed, and i don't want to touch the parser yet (i need some supervising on this).
(i did not altered init) (and i'm still not a nimble or github ninja - thank you for verbosity)
I would be happy if you would share your thoughts - and show a way forward.

Test cases: nimble install -ed library with or without srcDir,  
nimble develop library with or without srcDir  

Binary pkgs working if .nimle contains installExt = @["nim"].

Has some debugEchos, as it is not final yet ;)
 
Extended nimble with the `examples` command (as template is a reserved word).
Frameworks may add Application Templates to the nimble package, like SimpleApp, AdvancedApp, etc,
or Demo applications may be shipped with the package.
Added `examples` directory to the folder structure.
 
**From Readme:**
### nimble examples

The ``examples`` command copies from the packages examples directory to the
working directory. So you may distribute boilerplates, demos with your package.
```
    myproject$ nimble examples [pkgname] [samplename]
    myproject$ nimble examples [pkgname@pkgversion] [samplename]
```
The interactive version loads the folder tree from examples folder to choose from.  
You can hide subdirectories from the list, if you place ``_`` in the parents 
name (eg: chapter_1)
```
    myproject$ nimble examples [pkgname]
```

### Examples

You may wish to include boilerplates or demos with your package,
for this purpose, create an `examples` subdirectory, where your main file is.
(eg: src/examples)

```
.                   # The root directory of the project
├── LICENSE
├── README.md
├── foobar.nimble   # The project .nimble file
└── src
    └── foobar.nim  # Imported via `import foobar`
    └── examples    # Folder for Examples/Templates
        ├── demo1         # Demo application
         |   └── demo.nim
        ├── simpleapp     # Application template
         |   └── main.nim
         |   └── ...
        └── foobar
            └── subfoo    # can be nested
                └── foobar.nim

```

### CODE REVIEW

**Comment by dom96** [comment]
Tests still failing. Can't accept this unless they succeed, also not sure if you followed my advice from previous PRs.

**Comment by nais314** [comment]
Ooops, sorry!
I tried to catch up with you - but this is out of my league.
I'm closing this PR.
Best Wishes! :)

**Comment by alehander42** [comment]
hey @nais314 dont stop! so it seems your prompt examples are failing: are you sure we can fix them in travis? do you think of any reasons they might fail in such a environment? can we pass e.g. `-y` to them or something similar(i am not sure its easy to test prompts at all)

**Comment by nais314** [comment]
Thank You alehander42! and thanks for your findings!
I will look into it! (in a few days) (and i will re-read the past comments) (and look around travis) (if succeed in some way, i will PR the results)

**Pull request closed without merging**
