### PR TITLE
Fixed currently built package search path.

### PR DESCRIPTION
**Pull request by yglukhov**
This is a really quick fix. I don't mind if you fix it in some more appropriate way ;)

### CODE REVIEW

**Comment by dom96** [comment]
Is this related to: https://travis-ci.org/yglukhov/nimx/builds/99660730#L720 ?

**Comment by dom96** [comment]
What does ``nimble test`` do? That's what fails right?

**Comment by yglukhov** [comment]
> Is this related to: https://travis-ci.org/yglukhov/nimx/builds/99660730#L720 ?

Exactly

> What does nimble test do? That's what fails right?

https://github.com/yglukhov/nimx/blob/update-nimble/nimx.nimble
Currently it works, but will fail if you comment line 26

**Comment by yglukhov** [comment]
I no longer remember why i wrote it. Closing.

**Comment by dom96** [comment]
I think I know what the problem is, will reopen as a reminder for myself :)

**Comment by dom96** [comment]
I now think that we can close this. If this is still a problem it is bound to resurface again as an issue :)

**Pull request closed without merging**
