### PR TITLE
Fixed getPkgDir

### PR DESCRIPTION
**Pull request by yglukhov**

### CODE REVIEW

**Comment by genotrance** [comment]
Curious on this - `getPkgDir()` is not documented in nimscript nor nimble. How are users expected to find this and use it?

Meanwhile, `thisDir()` does exist in `nimscript` and is documented, just fixed it in #827.

cc @alaviss @dom96

**Comment by dom96** [comment]
Hrm, perhaps `getPkgDir` predates it? But yeah, docs would have been nice.

**Comment by genotrance** [comment]
Considering its not documented, I propose deprecating `getPkgDir()` and eventually remove.

**Comment by dom96** [comment]
CC @yglukhov

**Comment by yglukhov** [comment]
> Considering its not documented, I propose deprecating getPkgDir() and eventually remove.

Fine by me.

**Pull request merged**
