### PR TITLE
Fix forge aliases with SAT solver

### PR DESCRIPTION
**Pull request by xTrayambak**
The SAT solver seems to have borked the forge alias logic. This PR fixes it.

### CODE REVIEW

**Comment by jmgomez** [comment]
@xTrayambak thanks. Can you add a test case?

**Comment by xTrayambak** [comment]
@jmgomez Sorry, I'm not quite sure what to write a test-case for here. I've never really worked with the Nimble SAT solver, so I can't do that.

**Comment by jmgomez** [comment]
@xTrayambak you dont need to test anything specific to SAT, just an integration tests where you run `nimble install` on a package that uses the `pv.name.isForgeAlias` code path

**Comment by xTrayambak** [comment]
Alright. I'll wait for this one to run.

**Pull request merged**
