### PR TITLE
Fix #110 : use '^' rather than '-' for list negative indexes

### LINKED ISSUE #110: Installer: use '^' instead of '-'; negative indexing is obsolete
OS: Debian Jessie RC2: 3.16.0-4-amd64
~/github/nimble$ nim c -r src/nimble install
...
lib/pure/osproc.nim(779, 6) Warning: raiseOSError is deprecated [Deprecated]
lib/pure/osproc.nim(701, 9) Hint: 'osproc.startProcessAuxSpawn(data: TStartProcessData)' is declared but not used [XDeclaredButNotUsed]
Hint: pegs [Processing]
Hint: unicode [Processing]
Hint: json [Processing]
Hint: lexbase [Processing]
Hint: algorithm [Processing]
Hint: sets [Processing]
lib/pure/collections/sets.nim(801, 5) Hint: 'sets.testModule()' is declared but not used [XDeclaredButNotUsed]
Hint: sequtils [Processing]
Hint: packageinfo [Processing]
Hint: parsecfg [Processing]
Hint: version [Processing]
**/home/jdunlap/github/nimble/src/nimblepkg/version.nim(142, 21) Error: use '^' instead of '-'; negative indexing is obsolete**

### PR DESCRIPTION
**Pull request by JCavallo**
Just following the compiler's hint.

### CODE REVIEW

**Comment by dom96** [comment]
Please use ``str.len-1`` instead of ``^1``

**Comment by saml** [comment]
looks like these are the same:

```nim
arr[0 .. arr.len() - N]
arr[0 .. ^N]
```

**Comment by dom96** [comment]
They are but the latter won't work with an older compiler.

**Comment by JCavallo** [comment]
Done.

Tests do not run on my machine, but that may be because of some missing configuration.

**Comment by saml** [comment]
:+1:

**Pull request merged**
