### PR TITLE
Fixed chcp call on vista and newer

### PR DESCRIPTION
**Pull request by vegansk**
https://github.com/nim-lang/nimble/pull/149 breaks down code page change on Vista and newer. This PR fixes .bat file generation on these systems. Tested on Win XP, Vista, 8.1

### CODE REVIEW

**Comment by dom96** [comment]
Hrm, this is a bit ugly. But i'll merge it.

**Comment by vegansk** [comment]
@dom96, whats wrong with it, to do it right next time? :-)

**Comment by dom96** [comment]
It's nothing wrong with your code. It's just another thing to maintain though...

**Comment by dom96** [comment]
My intuition was correct, broken already because the ``windows`` module was moved to a separate repo :\

**Pull request merged**
